name: Release npm
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Configure committer
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Publish
        id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{secrets.NPM_TOKEN}}
      - name: No Changes
        if: steps.publish.outputs.type == 'none'
        run: echo "There are no changes to the version."
      - name: Release
        if: steps.publish.outputs.type != 'none'
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}
        with:
          tag_name: v${{steps.publish.outputs.version}}
          body: body_v${{steps.publish.outputs.version}}
          draft: false
          prerelease: false
